import { GlowingEffect } from "@/components/common/glowing-effect";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

const faqs = [
  {
    question: "How does LexiFlix personalize my study plan?",
    answer:
      "LexiFlix starts with an adaptive CEFR placement check (A1–C2) or a manual level override. When generating a vocabulary pack, you can configure your study settings, including target vocabulary types (words, phrasal verbs, idioms, slang), CEFR selection window (same level, one level above, or all levels above), known-term handling (exclude, down-rank, or include), and custom instructions.",
  },
  {
    question: "How do movies and subtitles get analyzed in LexiFlix?",
    answer:
      "We check if a title already has cached analysis. If not, LexiFlix fetches subtitles transiently on-demand from OpenSubtitles without storing the raw subtitle files. The text runs through a dual-pipeline: an internal FastAPI service for fast, spaCy-based NLP lemma and POS parsing, and a batched Gemini LLM pipeline to isolate phrasal verbs, idioms, and slang.",
  },
  {
    question: "What is included in a generated study pack?",
    answer:
      "A study pack contains up to 100 customized vocabulary cards. Each card is hydrated with plain-English definitions and fresh, newly-written example sentences generated by Gemini. It also includes natural pronunciation audio generated by AWS Polly and, where applicable, best-effort contextual images.",
  },
  {
    question: "How does my study progress sync across titles?",
    answer:
      "LexiFlix maintains cross-pack coherence. Active cards use a legacy SM-2 baseline scheduler with four rating grades (Again, Hard, Good, Easy) and sub-day learning steps. When you master a term in one pack, or mark a term as Globally Known or Ignored, that knowledge state immediately propagates across all active cards and future generation runs, ensuring your study plan stays consistent.",
  },
];

export function FAQSection() {
  return (
    <section
      id="faq"
      className="relative overflow-hidden bg-transparent px-6 py-8 "
      aria-labelledby="faq-heading"
    >
      <div className="mx-auto max-w-6xl rounded-[2.25rem] px-8 py-12 sm:px-10 lg:px-14">
        <div className="grid gap-10 lg:grid-cols-[minmax(0,1.05fr)_minmax(0,0.95fr)]">
          {/* Header Content */}
          <div className="space-y-6">
            <span className="inline-flex items-center gap-2 rounded-full border border-indigo-200/60 bg-white/70 px-4 py-1 text-xs font-semibold uppercase text-indigo-600 shadow-sm backdrop-blur font-ubuntu-mono dark:border-indigo-900/40 dark:bg-slate-950/50 dark:text-indigo-200">
              FAQ
            </span>
            <h2 id="faq-heading" className="text-balance text-3xl font-semibold sm:text-4xl">
              Everything you're curious about, answered in two taps
            </h2>
            <p className="text-balance text-base text-muted-foreground sm:text-lg">
              Our learners ask smart questions. We built a compact, tappable FAQ so you get to the
              good stuff quickly—no endless scrolling.
            </p>
            <div className="flex flex-wrap gap-2 text-xs font-medium uppercase  text-muted-foreground font-ubuntu-mono">
              <span className="inline-flex items-center gap-2 rounded-full border border-indigo-200/50 bg-white/65 px-4 py-1.5 dark:border-indigo-900/50 dark:bg-slate-950/60">
                <span className="size-2 rounded-full bg-indigo-500" aria-hidden="true" />
                Updated weekly
              </span>
              <span className="inline-flex items-center gap-2 rounded-full border border-purple-200/50 bg-white/65 px-4 py-1.5 dark:border-purple-900/50 dark:bg-slate-950/60">
                <span className="size-2 rounded-full bg-purple-500" aria-hidden="true" />
                Learner feedback
              </span>
            </div>
          </div>

          {/* FAQ Accordion */}
          <Card className="relative overflow-hidden border border-indigo-200/60 bg-white/80 shadow-lg backdrop-blur-sm dark:border-indigo-900/40 dark:bg-slate-950/80 dark:shadow-2xl">
            <GlowingEffect
              blur={6}
              borderWidth={1}
              spread={32}
              proximity={40}
              inactiveZone={0.2}
              className="opacity-15"
              glow
              disabled={false}
            />
            <CardHeader className="relative pb-3 text-center">
              <CardTitle className="text-lg font-semibold text-slate-900 dark:text-slate-100">
                Quick answers whenever you need them
              </CardTitle>
              <CardDescription className="text-slate-600 dark:text-slate-400 mt-1 text-sm">
                Tap to expand a question—each one keeps your place so you can skim without losing
                focus.
              </CardDescription>
            </CardHeader>
            <CardContent className="relative px-0 pb-1">
              <Accordion
                type="single"
                collapsible
                className="divide-y divide-indigo-100/80 [--radix-accordion-content-text-color:theme(colors.slate.600)] dark:divide-indigo-800/50"
              >
                {faqs.map(({ question, answer }, index) => (
                  <AccordionItem
                    value={`faq-${index}`}
                    key={question}
                    className="group border-none"
                  >
                    <AccordionTrigger className="px-6 py-4 text-left text-sm font-medium text-slate-900 hover:text-indigo-600 transition-colors duration-200 hover:no-underline group-hover:bg-indigo-50/50 dark:text-slate-100 dark:hover:text-indigo-300 dark:group-hover:bg-indigo-950/20">
                      <span className="flex items-center gap-3">
                        <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-indigo-100 text-xs font-semibold text-indigo-600 group-hover:bg-indigo-200 dark:bg-indigo-900/50 dark:text-indigo-300 dark:group-hover:bg-indigo-800/50">
                          {index + 1}
                        </span>
                        {question}
                      </span>
                    </AccordionTrigger>
                    <AccordionContent className="px-6 pb-4 pt-2 text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                      <div className="ml-8 border-l-2 border-indigo-200/60 pl-4 dark:border-indigo-800/60">
                        {answer}
                      </div>
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  );
}
